# General

* Everything (modules, class definition, functions, objects, etc) in Python is an object.
* "Object-oriented programming is all about interface." (p433)
* duck typing: implement the methods that fulfil the protocol; no need to inherit from any classes (p404)
* "A is B because A behaves like B".
* think of variables as sticky notes (fig 6–1 and ex 6–2, p203) not like boxes
* `==` vs `is`: `==` (through `__eq__` method) compares the values of objects; `is` compares their identities; when comparing to a singleton (e.g. `None`) (p206, 567)

# French Deck
The first example in Fluent Python tells a lot. 

Implement `__len__` and `__getitem__`, then we got many functions for free. 

In [1]:
import collections

In [2]:
Card = collections.namedtuple('Card', ['rank', 'suit'])

class FrenchDeck:
    ranks = [str(n) for n in range(2,11)] + list('JQKA')
    suits = 'spades diamonds clubs hearts'.split()
    
    def __init__(self):
        self._cards = [Card(rank, suit) for suit in self.suits for rank in self.ranks]

    def __len__(self):
        return len(self._cards)
    
    def __getitem__(self, position):
        return self._cards[position]

In [3]:
deck = FrenchDeck()

In [4]:
# length & position, of course
len(deck), deck[0], deck[-1]

(52, Card(rank='2', suit='spades'), Card(rank='A', suit='hearts'))

In [5]:
# choice
from random import choice
choice(deck), choice(deck)

(Card(rank='K', suit='clubs'), Card(rank='Q', suit='diamonds'))

In [6]:
# __getitem__ -> advanced indexing
deck[:3], deck[12::13]

([Card(rank='2', suit='spades'),
  Card(rank='3', suit='spades'),
  Card(rank='4', suit='spades')],
 [Card(rank='A', suit='spades'),
  Card(rank='A', suit='diamonds'),
  Card(rank='A', suit='clubs'),
  Card(rank='A', suit='hearts')])

In [7]:
# __getitem__ -> iterable
for c in deck[1:4]:
    print(c)

Card(rank='3', suit='spades')
Card(rank='4', suit='spades')
Card(rank='5', suit='spades')


In [8]:
# reverse
for c in reversed(deck[1:3]):
    print(c)

Card(rank='4', suit='spades')
Card(rank='3', suit='spades')


In [9]:
# 'in' operation through sequential scan
Card('Q', 'hearts') in deck, Card('7', 'beasts') in deck

(True, False)

In [10]:
# sorting
suit_values = dict(spades=3, hearts=2, diamonds=1, clubs=0)

def spades_high(card):
    rank_value = FrenchDeck.ranks.index(card.rank)
    return rank_value * len(suit_values) + suit_values[card.suit]

In [11]:
spades_high(Card('K', 'hearts'))
sorted(deck, key=spades_high)[:3]

[Card(rank='2', suit='clubs'),
 Card(rank='2', suit='diamonds'),
 Card(rank='2', suit='hearts')]

In [12]:
# Monkey Patching!
from random import shuffle
# monkey patchinig: can add a function later as long as the signiture is consistent
def set_card(deck, position, card):
    deck._cards[position] = card
FrenchDeck.__setitem__ = set_card
shuffle(deck) # this would raise an error if not patched. 
deck[:4]

[Card(rank='10', suit='hearts'),
 Card(rank='Q', suit='clubs'),
 Card(rank='J', suit='diamonds'),
 Card(rank='Q', suit='hearts')]

# == vs is
* ==: to compare values
* is: to compare ids

In [13]:
# with list
x1 = [1,2,3]
x2 = x1
x3 = [1,2,3]
print('x1 is x2 (id comparision):', x1 is x2)
print('x1 is x3 (id comparision):', x1 is x3)
print('x1 == x3 (value comparision):', x1 == x3)

x1 is x2 (id comparision): True
x1 is x3 (id comparision): False
x1 == x3 (value comparision): True


In [14]:
# == works for dictionary as well
d1 = {1:2, 2:4}
d2 = {1:20, 2:40}
d3 = {1:2, 2:4}
print('d1 == d2', d1 == d2)
print('d1 == d3', d1 == d3)

d1 == d2 False
d1 == d3 True


# Using \* : Grabbing Excess Iterms and Unpacking

In [15]:
# grabbing
# the remainder
a,b,*rest = range(5)
print((a,b,rest))
a,*body,c,d = range(5)
print((a, body, c, d))
*head,b,c,d = range(5)
print((head, b,c,d))

(0, 1, [2, 3, 4])
(0, [1, 2], 3, 4)
([0, 1], 2, 3, 4)


In [16]:
# unpacking
print( (*range(4), 4) )
print( (*range(4),4,*(5,6,7)))

(0, 1, 2, 3, 4)
(0, 1, 2, 3, 4, 5, 6, 7)


In [17]:
*range(4),4,*(5,6,7)

(0, 1, 2, 3, 4, 5, 6, 7)

# Exceptions
* `try`: try a code block. 
* `except`: handle an error
* `else`: execute code when no error. 
* `finally`: execute regardless. 

In [18]:
def f_ex(x):
    try:
        if x == 1:
            print(x)
        elif x == 2:
            print(no_variable) # this will raise an exception (NameError)
        else:
            z = str(x) + 1 # this will raise an exception that is not NameError
    except NameError: # handle a name error
        print('name error')
    except: # handle any other errors
        print('other error')
    else:
        print('else block')
    finally:
        print('finally block')

print('*** no error ***')
f_ex(1)
print('*** NameError ***')
f_ex(2)
print('*** Other Error ***')
f_ex(3)

*** no error ***
1
else block
finally block
*** NameError ***
name error
finally block
*** Other Error ***
other error
finally block


# Built-in functions & objects

## functions

In [19]:
class C1:
    def __init__(self, a: int):
        '''
        To show with help()
        '''
        self.a = a
        self.b = a + 2
    def fun1(self) -> int:
        return self.a
    def _fun2(self) -> int:
        return self.b
    def __fun3(self) -> int:
        return self.a + self.b

In [20]:
# help, dir
print('*** help(C1) ***')
print(help(C1)) # does not show _fun2 and __fun3
print('*** dir(C1) ***')
print(dir(C1)) # _fun2 is listed. __fun3 is listed is _C1_fun3

*** help(C1) ***
Help on class C1 in module __main__:

class C1(builtins.object)
 |  C1(a: int)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, a: int)
 |      To show with help()
 |  
 |  fun1(self) -> int
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)

None
*** dir(C1) ***
['_C1__fun3', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_fun2', 'fun1']


In [21]:
# id: id of class is different from id of an instance (of course)
c1 = C1(2)
print('id(C1): ', id(C1))
print('id(c1): ', id(c1))

id(C1):  94548093681728
id(c1):  140264242553488


## List & Tuple
* tuple is immutable and list is mutable. 
* mutable operators (`extend`, `append`, `reverse`, `sort`, etc) on list are in-place

In [22]:
# operators
L = list('aeioghe')
L.append('x') # in-place
L.extend('gegage') # in-place
L.insert(3, 'y')
L.remove('e') # remove the first occurence
L.reverse() # reverse in-place
del L[2:3] # delete. what a strange syntax
print('L:', L)
print('count of "e":', L.count('e'))
print('index of x:', L.index('x'))
L.sort()
print('L, sorted:', L)
L.clear()
print('L, clear:', L)

L: ['e', 'g', 'g', 'e', 'g', 'x', 'e', 'h', 'g', 'o', 'y', 'i', 'a']
count of "e": 3
index of x: 5
L, sorted: ['a', 'e', 'e', 'e', 'g', 'g', 'g', 'g', 'h', 'i', 'o', 'x', 'y']
L, clear: []


In [23]:
# comparison to sorted. 
L = list('ge9pauie')
L_s = sorted(L) # this is out-of-place operator
print('sorted:', sorted(L_s))

sorted: ['9', 'a', 'e', 'e', 'g', 'i', 'p', 'u']


## Dictionary

Different types of dictionaries
* `dict`: standard dictionary 
* `defaultdict`: dictionary with default specification
* `OrderedDict`: more or less "legacy" now. `dict` since Python 3.6 keeps the insertion order. 
* `ChainMap`: to chain multiple dictionaries. 
* `Counter`: to keep track of occurrences
* `UserDict`: subclass it. 
* `TypedDick`: to learn
* `shelve.Shelf`: to learn

see also [this page](https://realpython.com/python-defaultdict/)

Note: `d.get(k)` will return `None` whether `d` is of type `dict` or `defaultdict`. 


In [24]:
# use `setdefault` when inserting a key to a dictionary.

# example: sentence -> dictionary of letter to list of indices
sentence = 'A is B because A behaves like B'
l2i = {} # or, dict()
for i, l in enumerate(sentence):
    l2i.setdefault(l, []).append(i)
print(l2i)

{'A': [0, 15], ' ': [1, 4, 6, 14, 16, 24, 29], 'i': [2, 26], 's': [3, 12, 23], 'B': [5, 30], 'b': [7, 17], 'e': [8, 13, 18, 22, 28], 'c': [9], 'a': [10, 20], 'u': [11], 'h': [19], 'v': [21], 'l': [25], 'k': [27]}


In [25]:
# `.keys()`, `.values()`, `.items()` -> returns objects `dict_keys`, `dict_values`, `dict_items`
# They are iterable:
[v for v in l2i.items()][:2]
# But, not subscriptable. 
try: 
    l2i.items()[0]
except Exception as e:
    print(e)
# To make it subscriptable, make it into a list
list(l2i.items())[2]
# To peak the first item, make it into an iterator & call next
next(iter(l2i.items()))

'dict_items' object is not subscriptable


('A', [0, 15])

In [26]:
# alternatively, there is `defaultdict`
from collections import defaultdict

# by specifying `list', the default value is set to `list()`
l2i_dd = defaultdict(list) 
for i, l in enumerate(sentence):
    l2i_dd[l].append(i)
print(l2i_dd)

# to count
l2c_dd = defaultdict(int) # or float to keep the value in float
for i, l in enumerate(sentence):
    l2c_dd[l] += 1
print(l2c_dd)

defaultdict(<class 'list'>, {'A': [0, 15], ' ': [1, 4, 6, 14, 16, 24, 29], 'i': [2, 26], 's': [3, 12, 23], 'B': [5, 30], 'b': [7, 17], 'e': [8, 13, 18, 22, 28], 'c': [9], 'a': [10, 20], 'u': [11], 'h': [19], 'v': [21], 'l': [25], 'k': [27]})
defaultdict(<class 'int'>, {'A': 2, ' ': 7, 'i': 2, 's': 3, 'B': 2, 'b': 2, 'e': 5, 'c': 1, 'a': 2, 'u': 1, 'h': 1, 'v': 1, 'l': 1, 'k': 1})


In [27]:
# counter example
from collections import Counter
ct = Counter(sentence)
print(ct)

Counter({' ': 7, 'e': 5, 's': 3, 'A': 2, 'i': 2, 'B': 2, 'b': 2, 'a': 2, 'c': 1, 'u': 1, 'h': 1, 'v': 1, 'l': 1, 'k': 1})


In [28]:
# UserDict example
from collections import UserDict
class StrKeyDict(UserDict):
    
    def __missing__(self, key):
        if isinstance(key, str):
            raise KeyError(key)
        return self[str(key)]
    
    def __contain__(self, key):
        return str(key) in self.data
    
    def __setitem__(self, key, item):
        self.data[str(key)] = item
        
sud = StrKeyDict()
sud[2] = 'two'
print(sud)
try:
    sud[4]
except:
    print('error')

{'2': 'two'}
error


In [29]:
# Merging
x, y, z = {'a':1, 'b':2}, {'c':3, 'd':4}, {'e':5, 'f':6}
xyz = {**x, **y, **z}
print(xyz)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}


In [30]:
# sorting by key
d = {'c':3, 'd':4, 'b':2, 'a':1}
print('method 1:', {k:d[k] for k in sorted(d)})
print('method 2:', {k:v for k,v in sorted(d.items())})


method 1: {'a': 1, 'b': 2, 'c': 3, 'd': 4}
method 2: {'a': 1, 'b': 2, 'c': 3, 'd': 4}


## Set
elements must be hashable.

In [31]:
# empty set is set(), not {}, which is an empty dictionary
empty_set = set()
# non-empty sets are specified using {}
set_one = {1}
set_two = {1,2}

In [32]:
# element should be hashable
try:
    set([[1,2],[3,4]])
except Exception as e:
    print(e)

unhashable type: 'list'


## String

In [33]:
# formatting
string1, string2 = 'string1', 'string2'
## using f string
print(f'f string: {string1}')
## using %.
print('using %% %s %s' % (string1, string2))
## {} and format function (this is the same as f string, but old way)
print('using braces {}'.format((string1))) # how on earth can we put {} into the string???

f string: string1
using % string1 string2
using braces string1


In [34]:
# string is sort of a list when it comes to multiplication
'cat' * 3

'catcatcat'

In [35]:
# string methods
print('123'.isnumeric(), 'abc'.isalpha(), 'ab23'.isalnum())
print([m for m in dir('123') if not m.startswith('_')])

True True True
['capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


## map, filter, reduce

An old way (Python 2). Mostly replaced by listcomp and genexpr. 

In [36]:
def factorial_rec(n):
    return 1 if n < 1 else n * factorial_rec(n-1)

print('map & filter:', list(map(factorial_rec, filter(lambda n: n%2, range(6)))))
print('listcomp:', [factorial_rec(n) for n in range(6) if n%2])

map & filter: [1, 6, 120]
listcomp: [1, 6, 120]


In [37]:
# reduce
from functools import reduce
from operator import add
print('reduce & add:', reduce(add, range(4)))
print('sum:', sum(range(4)))

reduce & add: 6
sum: 6


## partial
freeze some arguments. more flexible than `lambda`

In [38]:
from functools import partial
add_3 = partial(add, 3)
add_3(4)

7

# Generator

## yield vs recursion

* some of recursive functions can be writtin using `yield`
* `yield from` is also interesting - examples to add later

In [39]:
# factorial using yield
def factorial_yield(n):
    k = 0 # track the index
    f = 1 # track the actual value
    while k <= n:
        yield f
        k += 1
        f *= k
# factorial up to 10
fy = factorial_yield(10)
print('using yield    ', [f for f in fy])

# using recursive version (see above)
# this would be slower
print('using recursion', [factorial_rec(n) for n in range(11)])

using yield     [1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800]
using recursion [1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800]


In [40]:
# fibonnacci

# using recursion
def fibonnacci(n):
    return n if n < 2 else (fibonnacci(n-2) + fibonnacci(n-1))

# using yield. 4-liner though. 
def fibonnacci_yield(n):
    k, f0, f1 = 0, 0, 1 # k: track the index, f0,f1: actual value
    while k <= n:
        yield f0
        k, f0, f1 = k+1, f1, f0+f1 # the following line is a bit of magic
        # alternatively,
        # k += 1
        # temp = f0
        # f0 = f1
        # f1 += temp

# fibonnacci up to 10
fb_y = fibonnacci_yield(10)
print('using yield    ', [f for f in fb_y])
print('using recursion', [fibonnacci(n) for n in range(11)])

using yield     [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
using recursion [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


## Generator, Iterable, Iterator

A generator is a type of iterator, which is iterable (Fluent Python p235)


In [41]:
# iterable vs iterator
# 1. list is iterable but not iterator (next does not work)
my_list = [1,2,3]
try:
    next(my_list)
except:
    print('error: called next function on iterable but not iterator')
# 2. call iter to make it an iterator
print('next(iter(my_list)):', next(iter(my_list)))
# 3. iterator is not subscriptable
try:
    iter(my_list)[0]
except:
    print('tried to subscript an iterator')
# both iterable and iterable are iterable: 
print('iterable:', [x for x in my_list])
print('iterator:', [x for x in iter(my_list)])

error: called next function on iterable but not iterator
next(iter(my_list)): 1
tried to subscript an iterator
iterable: [1, 2, 3]
iterator: [1, 2, 3]


In [42]:
# generator is an iterator. two common approaches
# 1) implement a separate generator class with __next__ and __iter__ methods
# 2) implement __iter__ method using yield to return an iterator

# demo with 2)
class MyGen:
    def __init__(self, string):
        self.string = string
    def __iter__(self):
        for s in self.string:
            yield s
my_gen = MyGen('abcde') # this is iterable but not iterator
print([s for s in my_gen])
print(next(iter(my_gen))) # iter makes it an iterable

['a', 'b', 'c', 'd', 'e']
a


# Class

* no static attributes (Fluent Python author does not think this is required)
* private attributes: use `__` as pre-fix (*debatable* convention though)
* Inheritance:
    * Python 3 constructor:
        ````python
        def __init__(self,a,b):
            super().__init__(a,b)
        ````
    * Method: Python 2 way was more complex to call. 
        * Python 3: `super().__setitem__(key,value)`
        * Python 2: `super(subclass,self).__setitem__(key,value)`
    * Do not subclass built-in types (e.g. `dict`, `list`, `str`) although not impossible. 
    * Multiple inheritance is a pain
    * Mixin class seems to be a nice way to handle multiple inheritance
* **Late Binding** rule: "A basic rule of object-oriented programming: the search for methods should always start from the class of the receiver (`self`), even when the call hapens inside a method imiplemented in a superclass." 
* Generic class: define a subclass by passing `Generic[T]`. 

## Inheritance & abstractmethod

In [43]:
# example in https://realpython.com/inheritance-composition-python/

from abc import ABC, abstractmethod

# employee, an abstract class. 
class Employee(ABC):
    def __init__(self, id, name):
        self.id = id
        self.name = name
    
    @abstractmethod
    def calculate_payroll(self):
        pass

class SalaryEmployee(Employee):
    def __init__(self, id, name, weekly_salary):
        super().__init__(id, name)
        self.weekly_salary = weekly_salary
    def calculate_payroll(self):
        return self.weekly_salary

class HourlyEmployee(Employee):
    def __init__(self, id, name, hours_worked, hour_rate):
        super().__init__(id, name)
        self.hours_worked = hours_worked
        self.hour_rate = hour_rate
    def calculate_payroll(self):
        return self.hours_worked * self.hour_rate
    
class CommissionEmployee(SalaryEmployee):
    def __init__(self, id, name, weekly_salary, commission):
        super().__init__(id, name, weekly_salary)
        self.commission = commission
    def calculate_payroll(self):
        fixed = super().calculate_payroll()
        return fixed + self.commission

# Duck Typing - no need to use inheritance as long as required methods are implemented. 
#
class DisgruntledEmployee:
    def __init__(self, id, name):
        self.id = id
        self.name = name
    def calculate_payroll(self):
        return 1000000

class PayrollSystem:
    def calculate_payroll(self, employees):
        print('calculating payroll')
        for employee in employees:
            print(f'payroll for: {employee.id} - {employee.name}')
            print(f'- check amount: {employee.calculate_payroll()}')
            

In [44]:
try:
    base_employee = Employee(0, 'Anna Bonn')
except:
    print('error: to instantiate abstract class')

salary_employee = SalaryEmployee(1, 'John Smith', 1500)
hourly_employee = HourlyEmployee(2, 'Jane Doe', 40, 15)
commission_employee = CommissionEmployee(3, 'Kevin Bacon', 1000, 250)
disgruntled_employee = DisgruntledEmployee(20000, 'Anonymous')
payroll_system = PayrollSystem()
payroll_system.calculate_payroll([
    salary_employee,
    hourly_employee,
    commission_employee, 
    disgruntled_employee
])

error: to instantiate abstract class
calculating payroll
payroll for: 1 - John Smith
- check amount: 1500
payroll for: 2 - Jane Doe
- check amount: 600
payroll for: 3 - Kevin Bacon
- check amount: 1250
payroll for: 20000 - Anonymous
- check amount: 1000000


## classmethod & staticmethod

The Python [tutorial](https://docs.python.org/3/tutorial/) does not mention `classmethod` and `staticmethod`. Maybe they are decorators? 

* `classmethod`: first argument is the class (not object) itself 
* `staticmethod`: no speicial first argument. a plain function that happens to live in a class body

In [45]:
# example from https://towardsdatascience.com/53-python-interview-questions-and-answers-91fa311eec3f

class CoffeeShop:
    specialty = 'espresso'
    
    def __init__(self, coffee_price):
        self.coffee_price = coffee_price
    
    # instance method
    def make_coffee(self):
        self.check_weather() # or CoffeeShop.check_weather()        
        print(f'Making {self.specialty} for ${self.coffee_price}')
    
    # static method    
    @staticmethod
    def check_weather():
        print('Its sunny')
    # class method
    @classmethod
    def change_specialty(cls, specialty):
        cls.specialty = specialty
        print(f'Specialty changed to {specialty}')

        

In [46]:
cs = CoffeeShop(1.0)
cs.make_coffee()

Its sunny
Making espresso for $1.0


In [47]:
CoffeeShop.check_weather()
cs.check_weather()

Its sunny
Its sunny


In [48]:
cs.change_specialty('drip coffee')
cs.make_coffee()

Specialty changed to drip coffee
Its sunny
Making drip coffee for $1.0


In [49]:
CoffeeShop.change_specialty('latte')
cs.make_coffee()

Specialty changed to latte
Its sunny
Making latte for $1.0


# Decorator

* function decorator: a callable that takes another function as an argument
* class decorator: a callable that takes another class as an argument

    ````python
    @decorate
    def target():
        print('running target()')
    ````
    is equivalent to
    ````python
    def target():
        print('running target()')
    target = decorate(target)
    ````
* **built-in** decorators
    * `functools.wraps`: copy relevant attributes
    * `functools.cache`,  `functools.lru_cache`, `functools.lru_cache()`: cache (3.9, 3.8, >3.2)
       
       This decorator is really good. 

In [50]:
# example
def deco(func):
    def inner():
        print('running inner()')
    return inner

@deco
def target():
    prini('running target()')
    
print(target())
print(target)

running inner()
None
<function deco.<locals>.inner at 0x7f91d0558290>


In [51]:
import functools
# show function name
def show_function_name(func):
    @functools.wraps(func)
    def named(*args, **kwargs):
        result = func(*args, **kwargs)
        name = func.__name__
        arg_lst = [str(arg) for arg in args]
        arg_lst.extend([f'{k}={v!r}' for k,v in kwargs.items()])
        arg_str = ','.join(arg_lst)
        print(f'{name}({arg_str})')
        return result
    return named

In [52]:
@show_function_name
def fibonnacci(n):
    return n if n < 2 else (fibonnacci(n-2) + fibonnacci(n-1))

fibonnacci(5)

fibonnacci(1)
fibonnacci(0)
fibonnacci(1)
fibonnacci(2)
fibonnacci(3)
fibonnacci(0)
fibonnacci(1)
fibonnacci(2)
fibonnacci(1)
fibonnacci(0)
fibonnacci(1)
fibonnacci(2)
fibonnacci(3)
fibonnacci(4)
fibonnacci(5)


5

In [53]:
@functools.lru_cache() # this is a magic. 
@show_function_name
def fibonnacci(n):
    return n if n < 2 else (fibonnacci(n-2) + fibonnacci(n-1))
fibonnacci(5)

fibonnacci(1)
fibonnacci(0)
fibonnacci(2)
fibonnacci(3)
fibonnacci(4)
fibonnacci(5)


5

# Closure

* FP p314: A closure is a function `f` with an extended scope that encompasses variables referenced in the body of `f` that are not global variables or local variables of `f`. Such variables come from the local scope of an outer function that encompasses `f`. 
* Basically, it references some variables outside the function. 

In [54]:
# class based example
# cumulative averager
class Averager():
    def __init__(self):
        self.series = [] # THIS is refernced by __call__ function. 
    def __call__(self, new_value):
        self.series.append(new_value)
        return sum(self.series)/ len(self.series)
avg = Averager()
print(avg(10), avg(11), avg(12))

10.0 10.5 11.0


In [55]:
# function based example
def make_averager():
    series = []
    def averager(new_value):
        series.append(new_value)
        return sum(series)/ len(series)
    return averager

avg = make_averager()
print(avg(10), avg(11), avg(12))

10.0 10.5 11.0


# Numpy

ultimately [here](https://numpy.org/doc/stable/user/index.html)

## Python array

In [1]:
# Before staring numpy, Python has its own array, which is like a list but must be homogenous elements. 
# But, it works very differently.
import array
X_array = array.array('i', [1,2,3])
Y_array = X_array * 2
print(Y_array)

array('i', [1, 2, 3, 1, 2, 3])


## now, numpy arrays

In [3]:
import numpy as np

In [4]:
# concat
a = np.array([1,2])
b = np.array([3,4,5])
np.concatenate((a,b))

array([1, 2, 3, 4, 5])

In [15]:
# np.newaxis (alias of None)
x = np.array([1,2,3])
y = np.array([4,5])
x[:,np.newaxis, np.newaxis] + y # make x as 2D. y broadcasts. 

array([[[5, 6]],

       [[6, 7]],

       [[7, 8]]])

In [17]:
# Ellipsis: repeated :
x4 = np.random.standard_normal((3,3,3,3))
print(x4[1,...,2])
print(x4[1,:,:,2])

[[-1.43997572  1.49390855  0.20585357]
 [-0.55726379  1.87814613 -1.02595348]
 [-0.86113962  0.04024694  1.02592993]]
[[-1.43997572  1.49390855  0.20585357]
 [-0.55726379  1.87814613 -1.02595348]
 [-0.86113962  0.04024694  1.02592993]]


In [24]:
# slice. allows to pass '0:2' as a variable. 
s12 = slice(0,2)
print(x4[0:2,0,0,0])
print(x4[s12,0,0,0])

[-2.2245668  -0.00357806]
[-2.2245668  -0.00357806]


In [31]:
x4[slice(1,None,None),0,0,0]

array([-0.00357806,  1.21378404])

# Pandas
ultimately, [here](https://pandas.pydata.org/docs/user_guide/)

In [58]:
import pandas as pd
from IPython.display import display

In [59]:
# stack and unstack is always confusing, which one is which? 
df = pd.DataFrame(data=[[1,2],[3,4]], columns=['a','b'])
display(df)
display(df.stack()) # stack: bring column to index
display(df.unstack()) # unstack: bring index to column

a  b
0  1  2
1  3  4

0  a    1
   b    2
1  a    3
   b    4
dtype: int64

a  0    1
   1    3
b  0    2
   1    4
dtype: int64

In [60]:
df

a  b
0  1  2
1  3  4

# END

In [61]:
def tree(cls, level=0):
    yield cls.__name__, level
    for sub_cls in cls.__subclasses__():
        yield from tree(sub_cls, level+1)


In [62]:
def display(cls):
    for cls_name, level in tree(cls):
        index = ' '*4 * level
        print(f'{index}{cls_name}')

In [63]:
display(BaseException)

BaseException
    Exception
        TypeError
            FloatOperation
            MultipartConversionError
            UFuncTypeError
                UFuncTypeError
                UFuncTypeError
                UFuncTypeError
                    UFuncTypeError
                    UFuncTypeError
            ApplyTypeError
        StopAsyncIteration
        StopIteration
        ImportError
            ModuleNotFoundError
            ZipImportError
            SQLAlchemyRequired
        OSError
            ConnectionError
                BrokenPipeError
                ConnectionAbortedError
                ConnectionRefusedError
                ConnectionResetError
                    RemoteDisconnected
            BlockingIOError
            ChildProcessError
            FileExistsError
            FileNotFoundError
            IsADirectoryError
            NotADirectoryError
            InterruptedError
                InterruptedSystemCall
            PermissionError
            