In [4]:
def u(*args):
    left = []
    right = []
    for i in range(0, len(args), 2):
        left.append(args[i])
        if i+1 < len(args):
            right.append(args[i+1])
    return (left, right)

In [9]:
f = ['x', 'y', 'y','y', 'z']
c = [630, 115, 320, 800, 450]
sorted(zip(f,c), key=lambda x:x[-1])

[('y', 115), ('y', 320), ('z', 450), ('x', 630), ('y', 800)]

In [2]:
import tensorflow as tf

In [3]:
x = tf.Variable(3, name="x")
y = tf.Variable(4, name='y')
f = x*x*y + y + 2

In [11]:
f.ndim

0

In [12]:
mnist = tf.keras.datasets.mnist

In [14]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [16]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [17]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [22]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.40446436, -0.25152043, -0.5243422 , -0.03705236,  0.4777838 ,
        -0.02151011, -0.77318525, -0.12770048,  0.21186319,  0.16097158]],
      dtype=float32)

In [23]:
tf.nn.softmax(predictions).numpy()

array([[0.14726992, 0.07642289, 0.05817528, 0.09470345, 0.15847336,
        0.09618684, 0.0453594 , 0.08649635, 0.12146983, 0.11544269]],
      dtype=float32)

In [24]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [26]:
loss_fn(y_train[:1], predictions).numpy()

2.3414626

In [27]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [28]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2940 - accuracy: 0.9155
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1436 - accuracy: 0.9569
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1068 - accuracy: 0.9683
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0856 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0727 - accuracy: 0.9769


In [29]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0722 - accuracy: 0.9789


[0.07220040261745453, 0.9789000153541565]

In [31]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [33]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [32]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.92196534e-07, 2.15955147e-08, 3.23119311e-05, 1.09324756e-04,
        2.34983023e-11, 4.00877838e-07, 3.80528915e-13, 9.99854565e-01,
        2.61750813e-07, 2.59774197e-06],
       [8.22602397e-06, 2.62009289e-05, 9.99842882e-01, 1.17659140e-04,
        9.20624229e-16, 3.28096962e-06, 1.09600364e-07, 4.81512920e-12,
        1.54763154e-06, 1.26442875e-11],
       [1.29612715e-07, 9.98576283e-01, 3.15362449e-05, 7.14441785e-06,
        1.21861885e-05, 4.84159682e-06, 4.74827812e-06, 1.28120161e-03,
        8.15312669e-05, 3.36005172e-07],
       [9.98919368e-01, 6.12300653e-07, 6.44792046e-04, 7.37206904e-07,
        1.60906586e-06, 2.34546314e-06, 9.59825265e-05, 1.20008488e-04,
        9.03387672e-07, 2.13505758e-04],
       [2.63498191e-06, 3.43572673e-08, 1.37198995e-05, 1.84392217e-08,
        9.88657534e-01, 5.75536546e-07, 7.82578013e-07, 3.44866930e-05,
        1.71968935e-07, 1.12900911e-02]], dtype=float32)>

In [34]:
predictions

array([[ 0.40446436, -0.25152043, -0.5243422 , -0.03705236,  0.4777838 ,
        -0.02151011, -0.77318525, -0.12770048,  0.21186319,  0.16097158]],
      dtype=float32)

In [35]:
y_train[:1]

array([5], dtype=uint8)