In [1]:
import os, sys
import shutil
import time
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objs as go


# include the folder
sys.path.append(os.path.join(os.getcwd(), os.path.pardir))

import ns2dspectral

%load_ext autoreload
%autoreload 2



In [2]:
def save_image(data, fn, cm="RdBu"):
    vmax = np.max(np.abs(data))
    sizes = np.shape(data)
    height = float(sizes[0]); width = float(sizes[1])
    fig = plt.figure()
    fig.set_size_inches(width/height, 1, forward=False)
    ax = plt.Axes(fig, [0., 0., 1., 1.])
    ax.set_axis_off()
    fig.add_axes(ax)
    ax.contourf(data, cmap=cm, vmin=-vmax, vmax=vmax, levels=20)
    plt.savefig(fn, dpi = 4*height, bbox_inches="tight", pad_inches=0) 
    plt.close()

pi2 = np.pi * 2.0

In [12]:
def clean_folder(folder):
    if os.path.exists(folder):
        shutil.rmtree(folder)
    time.sleep(0.5)
    os.makedirs(folder, exist_ok=True)

data_home_folder = os.path.join(os.path.expanduser('~'), 'SimulationData', 'NS2D')
output_folder = os.path.join(data_home_folder, 'output')
fig_folder = os.path.join(data_home_folder, 'fig')
clean_folder(output_folder)
clean_folder(fig_folder)

In [5]:
os.path.expanduser('~')

'/home/youngsuklee'

In [181]:
Mx = 64
My = 128
ns2d = ns2dspectral.NS2dSpectral(pi2, pi2, Mx, My, 1e-4, 1, .1)
np.max(ns2d.kw_factor[2])

1.0525333789097218

In [182]:
Mx = 64
My = 128
ns2d = ns2dspectral.NS2dSpectral(pi2, pi2, Mx, My, 1e-4, 1, .1)

output_folder = os.path.join(os.getcwd(), os.path.pardir, 'output')
fig_folder = os.path.join(os.getcwd(), os.path.pardir, 'fig')
clean_folder(output_folder)
clean_folder(fig_folder)

mtx_vor = np.random.standard_normal((My,Mx))
mtx_vor -= np.mean(mtx_vor)

#mtx_vor = ns2d.get_sample_init('cos')
mtx_vor_k = ns2d.fft2d(mtx_vor)
T = 1000
for n in range(T):
    mtx_vor_k = ns2d.march_forward_k(mtx_vor_k)
    if n % 100 == 0:
        mtx_vor = ns2d.ifft2d(mtx_vor_k)
        save_image(mtx_vor, os.path.join(fig_folder, str(T + n)))

AttributeError: 'NS2dSpectral' object has no attribute 'mtx_pad'

In [44]:
np.fft.fftfreq(4)

array([ 0.  ,  0.25, -0.5 , -0.25])

In [45]:
mtx_a = np.random.standard_normal((4,4))
np.fft.fft2(mtx_a)

array([[-2.74592903+0.j        ,  1.53924552+0.30316447j,
         1.15967256+0.j        ,  1.53924552-0.30316447j],
       [-2.33462616-0.45589905j,  4.07783848+4.89383767j,
        -0.60191508+3.45071668j, -0.6156043 +3.24392884j],
       [ 0.87082417+0.j        ,  1.16180547+2.21451536j,
         8.09840223+0.j        ,  1.16180547-2.21451536j],
       [-2.33462616+0.45589905j, -0.6156043 -3.24392884j,
        -0.60191508-3.45071668j,  4.07783848-4.89383767j]])

In [46]:
np.fft.rfft2(mtx_a)

array([[-2.74592903+0.j        ,  1.53924552+0.30316447j,
         1.15967256+0.j        ],
       [-2.33462616-0.45589905j,  4.07783848+4.89383767j,
        -0.60191508+3.45071668j],
       [ 0.87082417+0.j        ,  1.16180547+2.21451536j,
         8.09840223+0.j        ],
       [-2.33462616+0.45589905j, -0.6156043 -3.24392884j,
        -0.60191508-3.45071668j]])